name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-20.04, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Build
      run: cargo build --release --verbose

    - name: Set the binary name
      shell: bash
      run: echo "BINARY_NAME=$(python -c "import platform; uname=platform.uname(); print(f'lorust_{uname.system}_{uname.machine}.exe')")" >> "$GITHUB_ENV"

    - name: Renmae the built binary
      shell: bash
      run: mv target/release/lorust ./$BINARY_NAME

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: ${{ env.BINARY_NAME }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ env.BINARY_NAME }}
